"""empty message

Revision ID: 1d7585d1ef55
Revises: 
Create Date: 2025-03-19 18:00:12.261654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d7585d1ef55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=256), nullable=False))
        batch_op.create_index(batch_op.f('ix_pages_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('categories')
        batch_op.drop_column('reviews')
        batch_op.drop_column('descriprion')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('subjects')
        batch_op.drop_column('educational_institutions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('educational_institutions', mysql.JSON(), nullable=False))
        batch_op.add_column(sa.Column('subjects', mysql.JSON(), nullable=False))

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriprion', mysql.VARCHAR(length=256), nullable=False))
        batch_op.add_column(sa.Column('reviews', mysql.JSON(), nullable=False))
        batch_op.add_column(sa.Column('categories', mysql.JSON(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_pages_timestamp'))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
