"""empty message

Revision ID: 2686311391c9
Revises: 
Create Date: 2025-03-27 10:56:00.738166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2686311391c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grades_name'), ['name'], unique=True)

    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regions_name'), ['name'], unique=True)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types_of_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('types_of_work', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_types_of_work_name'), ['name'], unique=True)

    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlements_name'), ['name'], unique=True)

    op.create_table('educational_institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('educational_institutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_educational_institutions_name'), ['name'], unique=True)

    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('full_name', sa.String(length=64), nullable=False),
    sa.Column('about', sa.String(length=256), nullable=True),
    sa.Column('educational_institution', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['educational_institution'], ['educational_institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_educational_institution'), ['educational_institution'], unique=False)
        batch_op.create_index(batch_op.f('ix_teachers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_teachers_username'), ['username'], unique=True)

    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('link', sa.String(length=64), nullable=False),
    sa.Column('average_rating', sa.Float(precision=1), nullable=False),
    sa.Column('type_of_work_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['type_of_work_id'], ['types_of_work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_type_of_work_id'), ['type_of_work_id'], unique=False)

    op.create_table('teacher_subject',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'subject_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_page_id'), ['page_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_page_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_author_id'))

    op.drop_table('reviews')
    op.drop_table('teacher_subject')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_type_of_work_id'))
        batch_op.drop_index(batch_op.f('ix_pages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_pages_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_pages_subject'))
        batch_op.drop_index(batch_op.f('ix_pages_name'))
        batch_op.drop_index(batch_op.f('ix_pages_grade'))

    op.drop_table('pages')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_username'))
        batch_op.drop_index(batch_op.f('ix_teachers_email'))
        batch_op.drop_index(batch_op.f('ix_teachers_educational_institution'))

    op.drop_table('teachers')
    with op.batch_alter_table('educational_institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_educational_institutions_name'))

    op.drop_table('educational_institutions')
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlements_name'))

    op.drop_table('settlements')
    with op.batch_alter_table('types_of_work', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_types_of_work_name'))

    op.drop_table('types_of_work')
    op.drop_table('subjects')
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regions_name'))

    op.drop_table('regions')
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grades_name'))

    op.drop_table('grades')
    # ### end Alembic commands ###
