"""bug fixes

Revision ID: 799a25a0785f
Revises: d216b0fb7b66
Create Date: 2025-06-22 04:13:58.191180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '799a25a0785f'
down_revision = 'd216b0fb7b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('educational_institution',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('educational_institution',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
