"""empty message

Revision ID: a3888ea4b2ea
Revises: aa2e1ab90e1c
Create Date: 2025-04-16 16:25:40.240065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3888ea4b2ea'
down_revision = 'aa2e1ab90e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_subject', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
