"""empty message

Revision ID: a6ddac1dbc64
Revises: 2686311391c9
Create Date: 2025-03-27 10:58:25.518305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6ddac1dbc64'
down_revision = '2686311391c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=False))
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', mysql.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
