"""empty message

Revision ID: aa2e1ab90e1c
Revises: eb189241fb06
Create Date: 2025-04-04 17:37:38.387208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2e1ab90e1c'
down_revision = 'eb189241fb06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_reviews_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
