"""empty message

Revision ID: cfe40b36c9a6
Revises: 1d7585d1ef55
Create Date: 2025-03-20 13:12:50.421159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe40b36c9a6'
down_revision = '1d7585d1ef55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('reviews', sa.JSON(), nullable=False))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subjects', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('educational_institutions', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('educational_institutions')
        batch_op.drop_column('subjects')

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('reviews')
        batch_op.drop_column('categories')

    # ### end Alembic commands ###
