"""Add Moodle-like course and assignment structure

Revision ID: d216b0fb7b66
Revises: 0292b36498a4
Create Date: 2025-06-21 23:34:17.611567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd216b0fb7b66'
down_revision = '0292b36498a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=16), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint('teachers_ibfk_1', type_='foreignkey')
        batch_op.drop_index('ix_teachers_educational_institution')
        batch_op.drop_index('ix_teachers_email')
        batch_op.drop_index('ix_teachers_username')

    op.rename_table('teachers', 'users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'educational_institutions', ['educational_institution'],
                                    ['id'])
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_users_educational_institution'),
                              ['educational_institution'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('courses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=128), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('teacher_id', sa.Integer(), nullable=False),
                    sa.Column('subject_id', sa.Integer(), nullable=False),
                    sa.Column('grade_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
                    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
                    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('assignments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('course_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=128), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('due_date', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('course_enrollments',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('course_id', sa.Integer(), nullable=False),
                    sa.Column('enrollment_date', sa.DateTime(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'course_id')
                    )
    op.create_table('submissions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('assignment_id', sa.Integer(), nullable=False),
                    sa.Column('student_id', sa.Integer(), nullable=False),
                    sa.Column('submission_date', sa.DateTime(), nullable=False),
                    sa.Column('file_link', sa.String(length=256), nullable=True),
                    sa.Column('text_submission', sa.Text(), nullable=True),
                    sa.Column('grade', sa.Float(), nullable=True),
                    sa.Column('feedback', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
                    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint('followers_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('followers_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['follower_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['followed_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('notifications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('pages_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('pages_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('pages_ibfk_3', type_='foreignkey')
        batch_op.drop_index('ix_pages_grade')
        batch_op.drop_index('ix_pages_subject')
        batch_op.create_index(batch_op.f('ix_pages_course_id'), ['course_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['teacher_id'], ['id'])
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])
        batch_op.drop_column('grade')
        batch_op.drop_column('subject')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('reviews_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])

    with op.batch_alter_table('teacher_subject', schema=None) as batch_op:
        batch_op.drop_constraint('teacher_subject_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_subject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teacher_subject_ibfk_2', 'teachers', ['teacher_id'], ['id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reviews_ibfk_1', 'teachers', ['author_id'], ['id'])

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('grade', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pages_ibfk_3', 'teachers', ['teacher_id'], ['id'])
        batch_op.create_foreign_key('pages_ibfk_1', 'grades', ['grade'], ['id'])
        batch_op.create_foreign_key('pages_ibfk_2', 'subjects', ['subject'], ['id'])
        batch_op.drop_index(batch_op.f('ix_pages_course_id'))
        batch_op.create_index('ix_pages_subject', ['subject'], unique=False)
        batch_op.create_index('ix_pages_grade', ['grade'], unique=False)
        batch_op.drop_column('course_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notifications_ibfk_1', 'teachers', ['user_id'], ['id'])

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('followers_ibfk_1', 'teachers', ['followed_id'], ['id'])
        batch_op.create_foreign_key('followers_ibfk_2', 'teachers', ['follower_id'], ['id'])

    op.create_table('teachers',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('username', mysql.VARCHAR(length=64), nullable=False),
                    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
                    sa.Column('password_hash', mysql.VARCHAR(length=256), nullable=True),
                    sa.Column('full_name', mysql.VARCHAR(length=64), nullable=False),
                    sa.Column('about', mysql.VARCHAR(length=256), nullable=True),
                    sa.Column('educational_institution', mysql.INTEGER(), autoincrement=False,
                              nullable=False),
                    sa.ForeignKeyConstraint(['educational_institution'], ['educational_institutions.id'],
                                            name='teachers_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index('ix_teachers_username', ['username'], unique=True)
        batch_op.create_index('ix_teachers_email', ['email'], unique=True)
        batch_op.create_index('ix_teachers_educational_institution', ['educational_institution'],
                              unique=False)

    op.drop_table('submissions')
    op.drop_table('course_enrollments')
    op.drop_table('assignments')
    op.drop_table('courses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_educational_institution'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    # ### end Alembic commands ###
