"""empty message

Revision ID: eb189241fb06
Revises: 
Create Date: 2025-03-29 10:24:21.002109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb189241fb06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_pages_type_of_work'), ['type_of_work'], unique=False)
        batch_op.create_foreign_key(None, 'types_of_work', ['type_of_work'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pages_type_of_work'))
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)

    # ### end Alembic commands ###
