"""Add cascade delete for models

Revision ID: f3fc20414b0a
Revises: 05b9208daa31
Create Date: 2025-06-12 21:36:58.816745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3fc20414b0a'
down_revision = '05b9208daa31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.alter_column('follower_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('followed_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_followed', type_='foreignkey')
        batch_op.drop_constraint('fk_follower', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teachers', ['followed_id'], ['id'])
        batch_op.create_foreign_key(None, 'teachers', ['follower_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('notifications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teachers', ['user_id'], ['id'])

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index('ix_pages_timestamp')

    with op.batch_alter_table('teacher_subject', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_subject', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index('ix_pages_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notifications_ibfk_1', 'teachers', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_follower', 'teachers', ['follower_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_followed', 'teachers', ['followed_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('followed_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('follower_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
